#! /bin/sh

bspc config border_width        2
bspc config window_gap         12

bspc config normal_border_color "#402e2e"
bspc config focused_border_color "#978965"
bspc config active_border_color "#978965"
bspc config presel_border_color "#DFDFDF"
bspc config focused_locked_border_color "#978965"
bspc config active_locked_border_color "#978965"
bspc config normal_locked_border_color "#402e2e"
bspc config focused_sticky_border_color "#978965"
bspc config active_sticky_border_color "#978965"
bspc config normal_sticky_border_color "#402e2e"
bspc config focused_private_border_color "#978965"
bspc config active_private_border_color "#978965"
bspc config normal_private_border_color "#402e2e"
bspc config urgent_border_color "#2b3032"

bspc config split_ratio         0.5
bspc config borderless_monocle  false
bspc config gapless_monocle     true
bspc config focus_follows_pointer true

bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 0

bspc rule -a conky manage=off
bspc rule -a Thunar state=floating
bspc rule -a Steam state=tiled desktop=^6
bspc rule -a Chromium state=tiled desktop=^2
bspc rule -a Atom state=tiled desktop=^3
bspc rule -a LibreOffice state=tiled desktop=^5
bspc rule -a Plank layer=above manage=on locked=on border=off
bspc rule -a Spotify state=fullscreen desktop=^5
bspc rule -a Mathematica state=tiled desktop=^4
bspc rule -a crx_flejfacjooompmliegamfbpjjdlhokhj state=floating
bspc rule -a Evince state=tiled desktop=^4

bspc config top_padding 12
bspc config bottom_padding 55

bspc config external_rules_command "~/.config/bspwm/external_rules.sh"

# Autostart
xbindkeys
pulseaudio --start
#feh --no-startup-id --bg-fill ~/Pictures/wallpaper2.png
compton -cCGf --backend glx --paint-on-overlay --vsync opengl-swc &
plank &
bspc desktop -f 1 &
polybar bar1 &
redshift &
sxhkd &
xsetroot -cursor_name left_ptr
syndaemon -i 0.5 -t -K -R -d
dropbox &
bgchd -dir ~/Pictures/Wallpapers -bcknd feh -intv 30m
xautolock -time 10 -locker "i3lock-fancy -p"
