#! /bin/sh

bspc config border_width        2
bspc config window_gap         12

bspc config normal_border_color false
bspc config focused_border_color "#454545"
bspc config active_border_color "#454545"
bspc config presel_border_color "#DFDFDF"
bspc config focused_locked_border_color "#978965"
bspc config active_locked_border_color "#978965"
bspc config normal_locked_border_color "#402e2e"
bspc config focused_sticky_border_color "#978965"
bspc config active_sticky_border_color "#978965"
bspc config normal_sticky_border_color "#402e2e"
bspc config focused_private_border_color "#978965"
bspc config active_private_border_color "#978965"
bspc config normal_private_border_color "#402e2e"
bspc config urgent_border_color "#2b3032"

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config click_to_focus true

bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 0

bspc rule -a "Thunar" state=floating
bspc rule -a "Steam" state=tiled desktop=^6
bspc rule -a "Chromium" state=tiled desktop=^2
bspc rule -a "LibreOffice" state=tiled desktop=^5
bspc rule -a "Plank" manage=off
bspc rule -a "Mathematica" state=tiled desktop=^5
bspc rule -a "Evince" state=tiled
bspc rule -a "Subl3" state=tiled desktop=^3
bspc rule -a "Mendeley Desktop" state=tiled desktop=^3
bspc rule -a "Qt-subapplication" state=floating
bspc rule -a "Polybar" manage=off layer=above locked=on border=off
bspc rule -a "Pavucontrol" state=floating
bspc rule -a "Thunderbird" desktop=^5 state=tiled
bspc rule -a "Emacs" desktop=^3 state=tiled
bspc rule -a "octave_gui" desktop=^3 state=tiled
bspc rule -a "Firefox" desktop=^2 state=tiled
bspc rule -a "Oblogout" state=floating layer=above
bspc rule -a "Dialog" state=floating layer=above
bspc rule -a "Rofi" manage=off
bspc rule -a "Vivaldi-stable" state=tiled desktop=^2
bspc rule -a "Slack" state=tiled desktop=^5

bspc desktop 2 -l monocle
bspc desktop 5 -l monocle
bspc config top_padding 12
bspc config bottom_padding 12

bspc config external_rules_command "~/.config/bspwm/external_rules.sh"

feh --bg-center ~/Pictures/Wallpapers/CURRENT
compton -f --backend glx --paint-on-overlay --vsync opengl-swc&
polybar bar1 &
sxhkd &
xbindkeys
bspc desktop -f 1 &
redshift &
xsetroot -cursor_name left_ptr
syndaemon -i 0.5 -t -K -R -d
dropbox &
xset s noblank
udiskie &
setxkbmap -option grp:rctrl_rshift_toggle us,ru -variant ',phonetic' &
nm-applet &
blueman-applet &
cairo-dock -ao &
rfkill block bluetooth
